# Generated by Django 4.0.4 on 2022-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='json',
            field=models.JSONField(default=dict),
        ),
    ]
